sequenceDiagram
    participant Browser
    participant Server as studies.cs.helsinki.fi

    Browser->>+Server: GET /exampleapp/
    Server-->>-Browser: 200 OK (321 B)

    Browser->>+Server: GET /exampleapp/kuva.png
    Server-->>-Browser: 200 OK (89.35 KB)

    Browser->>+Server: GET /favicon.ico
    Server-->>-Browser: 404 Not Found

    Browser->>+Server: GET /exampleapp/notes
    Server-->>-Browser: 200 OK (439 B)

    Browser->>+Server: GET /exampleapp/main.css
    Server-->>-Browser: 200 OK (78 B)

    Browser->>+Server: GET /exampleapp/main.js
    Server-->>-Browser: 200 OK (579 B)

    Browser->>+Server: GET /exampleapp/data.json
    Server-->>-Browser: 200 OK (5.72 KB)

    Browser->>+Server: GET /favicon.ico
    Server-->>-Browser: 404 Not Found
